spring:
  hadoop:
    fsUri: hdfs://localhost:9000
    resourceManagerHost: localhost
  yarn:
    appName: yarn-demo
    applicationDir: /app/yarn-demo/
    fsUri: hdfs://localhost:9000
    rmAddress: localhost:8032
    schedulerAddress: localhost:9870
    client:
      startup:
        action: submit
      localizer:
        pattern:
          - "*.jar"
      files:
        - "file:target/yarn-demo-0.0.1-SNAPSHOT.jar"
      launchcontext:
        archiveFile: yarn-demo-0.0.1-SNAPSHOT.jar
    appmaster:
      containerCount: 1
      localizer:
        pattern:
          - "*.jar"
      launchcontext:
        archiveFile: yarn-demo-0.0.1-SNAPSHOT.jar
        arguments:
          --spring.profiles.active: container
